version: "3.8"

services:
  grafana:
    image: grafana/grafana:main
    ports:
      - "3000:3000"
    volumes:
      - "./config/grafana/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml"
      - "./config/grafana/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml"
      - "./config/grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "./config/grafana/dashboards/:/var/lib/grafana/dashboards"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
  
  loki:
    image: grafana/loki:2.4.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  cortex:
    image: quay.io/cortexproject/cortex:v1.11.0
    ports:
      - "9009:9009"
    volumes:
      - "./config/cortex/single-process-config-blocks.yaml:/etc/single-process-config-blocks.yaml"
      - "cortex-metrics:/DATA/tsdb/"
    command: -config.file=/etc/single-process-config-blocks.yaml

  tempo:
    image: grafana/tempo:latest
    ports:
      - "3200:3200"   # tempo
      - "55680:4317"  # otlp grpc
      - "55681:4318"  # otlp http
      - "9411:9411"   # zipkin
    volumes:
      - "./config/tempo/tempo-local.yaml:/etc/tempo.yaml"
      - "tempo-traces:/DATA/tempo/"
    command: -search.enabled=true -config.file=/etc/tempo.yaml

  jaeger:
    image: jaegertracing/all-in-one:1.30
    ports:
      - "5778:5778"   # jaeger config
      - "16686:16686" # jaeger frontend
      - "14268:14268" # jaeger
      - "14250:14250" # grpc

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    pid: host
    network_mode: host
    volumes:
      - "/:/host:ro,rslave"
    command: --path.rootfs=/host --web.listen-address=":9100"

volumes:
  cortex-metrics:
  tempo-traces: