# Generated by Django 4.0.1 on 2022-01-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Speciality',
            new_name='Specialty',
        ),
        migrations.RemoveField(
            model_name='vet',
            name='specialities',
        ),
        migrations.AddField(
            model_name='vet',
            name='specialties',
            field=models.ManyToManyField(related_name='vets', to='vets.Specialty'),
        ),
    ]
