receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: "0.0.0.0:4318"
        cors:
          allowed_origins:
            - http://localhost:8080

  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 5s
          static_configs:
            - targets: ['0.0.0.0:18888']
        - job_name: 'petclinic-api-gateway'
          scrape_interval: 5s
          scrape_timeout: 4s
          metrics_path: "/actuator/prometheus"
          static_configs:
            - targets: ['0.0.0.0:8080']
              labels:
                application: petclinic-api-gateway
        - job_name: 'petclinic-customers-service'
          scrape_interval: 5s
          scrape_timeout: 4s
          metrics_path: "/actuator/prometheus"
          static_configs:
            - targets: ['0.0.0.0:8081']
              labels:
                application: petclinic-customers-service
        - job_name: 'petclinic-visits-service'
          scrape_interval: 5s
          scrape_timeout: 4s
          metrics_path: "/actuator/prometheus"
          static_configs:
            - targets: ['0.0.0.0:8082']
              labels:
                application: petclinic-visits-service
        - job_name: 'petclinic-vets-service'
          scrape_interval: 5s
          scrape_timeout: 4s
          metrics_path: "/actuator/prometheus"
          static_configs:
            - targets: ['0.0.0.0:8083']
              labels:
                application: petclinic-vets-service
        - job_name: 'system-metrics'
          scrape_interval: 5s
          scrape_timeout: 4s
          static_configs:
            - targets: ['0.0.0.0:9100']
exporters:
  logging/traces:
    loglevel: info
  logging/metrics:
    loglevel: info
  logging/logs:
    loglevel: debug

  otlp/tempo:
    endpoint: 127.0.0.1:55680
    tls:
      insecure: true
  
  loki:
    endpoint: http://127.0.0.1:3100/loki/api/v1/push
    labels:
      resource:
        container.name: "container_name"
        host.name: "hostname"
        service.name: "service_name"
      attributes:
        severity: ""
        "Trace ID": "traceId"
        "Span ID": "spanId"

  prometheusremotewrite:
    endpoint: "http://localhost:9009/api/v1/push"
    external_labels:
      test: test
  
  jaeger:
    endpoint: localhost:14250
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: otlp
      exporters: 
        - logging/traces
        - otlp/tempo
        - jaeger

    metrics:
      receivers: 
        - otlp
        - prometheus
      exporters: 
        - logging/metrics
        - prometheusremotewrite
    logs:
      receivers: otlp
      exporters: 
        - logging/logs
        - loki
